# Generated by Django 5.2.3 on 2025-06-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='nationality',
            new_name='country',
        ),
    ]
