# Generated by Django 5.2.3 on 2025-07-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_nationality_author_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
